---
ID: "776dfd9e-ebe7-4030-b90a-c5c9b6c862fd"
Parent: "a1f7c913-e331-4172-bd26-0621dfbcd529"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Dynamic Sitemap XML/Change Frequency/Change Frequency For Templates/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160206T131731Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
