---
ID: "2abde922-f2b7-4f65-81c3-4190b16cd29e"
Parent: "9551d9f7-a66a-4a49-a705-b0b2918c0eb5"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Dynamic Sitemap XML/Change Frequency/Change Frequency For Items/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160206T134343Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
